### ISSUE TITLE
Error on read operations like getRow and getRows when disableCache is set to true

### ISSUE THREAD

**Issue by ccpacillos** [djansyle/mqsp#1]
When using `initialize` with `disableCache` set to` true`, it returns this error whenever I call read operations.

```
TypeError: Cannot read property 'get' of undefined
    at /vagrant/exp/http-graphql-barebones/node_modules/mqsp/build/cache.js:29:30
    at Generator.next (<anonymous>)
    at step (/vagrant/exp/http-graphql-barebones/node_modules/mqsp/build/cache.js:5:578)
    at /vagrant/exp/http-graphql-barebones/node_modules/mqsp/build/cache.js:5:808
    at new Promise (<anonymous>)
    at /vagrant/exp/http-graphql-barebones/node_modules/mqsp/build/cache.js:5:489
    at Cache.execute (/vagrant/exp/http-graphql-barebones/node_modules/mqsp/build/cache.js:35:21)
    at /vagrant/exp/http-graphql-barebones/node_modules/mqsp/build/mqsp.js:213:27
    at Generator.next (<anonymous>)
    at step (/vagrant/exp/http-graphql-barebones/node_modules/mqsp/build/mqsp.js:113:1119)
    at /vagrant/exp/http-graphql-barebones/node_modules/mqsp/build/mqsp.js:113:1360
    at Promise._execute (/vagrant/exp/http-graphql-barebones/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/vagrant/exp/http-graphql-barebones/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/vagrant/exp/http-graphql-barebones/node_modules/bluebird/js/release/promise.js:79:10)
    at /vagrant/exp/http-graphql-barebones/node_modules/mqsp/build/mqsp.js:113:1019
    at MQSP.cacheableRead (/vagrant/exp/http-graphql-barebones/node_modules/mqsp/build/mqsp.js:213:106)
```

My workaround as of the moment is to set the `cache` property of mqsp instance to a `falsy` value.

```
initialize({
  host: MYSQL_HOST,
  user: MYSQL_USER,
  password: MYSQL_PASSWORD,
  port: +MYSQL_PORT,
  database: MYSQL_DATABASE,
  connectionLimit: +MYSQL_CONNECTION_LIMIT,
  waitForConnections: true,
  acquireTimeout: 30000,
  multipleStatements: true,
  queueLimit: 0,
  disableCache: true,
});

const mqsp = new MQSP();
mqsp.cache = null;

export default mqsp;
```

**Comment by djansyle** [comment]
Solved the issue #2.
